import React, { useState, useCallback } from 'react';
import { AnimatePresence } from 'framer-motion';
import Lobby from './components/Lobby';
import AuctionRoom from './components/AuctionRoom';
import AuctionSummary from './components/AuctionSummary';
import LandingPage from './components/LandingPage';
import SignupPage from './components/SignupPage';
import MultiplayerHome from './components/MultiplayerHome';
import RoomLobby from './components/RoomLobby';
import { GameState, Team } from './types';
import { TEAMS, INITIAL_BUDGET } from './constants';

const App: React.FC = () => {
  const [gameState, setGameState] = useState<GameState>('landing');
  const [user, setUser] = useState<{ username: string } | null>(null);
  const [userTeam, setUserTeam] = useState<Team | null>(null);
  const [finalTeams, setFinalTeams] = useState<Team[]>([]);
  const [roomCode, setRoomCode] = useState<string | null>(null);
  const [isRoomHost, setIsRoomHost] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleGoToSignup = useCallback(() => setGameState('signup'), []);
  
  const handleGoToLobby = useCallback(() => setGameState('lobby'), []);

  const handleSignup = useCallback((username: string) => {
    setUser({ username });
    setGameState('lobby');
  }, []);

  const handleStartSinglePlayer = useCallback((selectedTeam: Omit<Team, 'budget' | 'players' | 'isAI' | 'isUser'>) => {
    const userTeamForAuction: Team = {
      ...selectedTeam,
      budget: INITIAL_BUDGET,
      players: [],
      isUser: true,
      isAI: false,
    };

    const aiTeams = TEAMS
      .filter(t => t.id !== selectedTeam.id)
      .slice(0, 3)
      .map(team => ({
        ...team,
        budget: INITIAL_BUDGET,
        players: [],
        isUser: false,
        isAI: true,
      }));

    const allTeamsForAuction = [userTeamForAuction, ...aiTeams];
    
    setUserTeam(userTeamForAuction);
    setFinalTeams(allTeamsForAuction);
    setGameState('auction');
  }, []);

  const handleGoToMultiplayer = useCallback(() => {
    setGameState('multiplayer-home');
  }, []);

  const handleCreateRoom = useCallback(() => {
    // In a real app, this would be generated by the backend.
    const newRoomCode = Math.random().toString(36).substring(2, 8).toUpperCase();
    setRoomCode(newRoomCode);
    setIsRoomHost(true);
    setGameState('room-lobby');
  }, []);
  
  const handleJoinRoom = useCallback((code: string) => {
    setRoomCode(code);
    setIsRoomHost(false);
    setGameState('room-lobby');
  }, []);
  
  const handleStartMultiplayerAuction = useCallback((teams: Team[], selectedUserTeam: Team, roomCodeParam: string) => {
    if (!teams || teams.length === 0 || !selectedUserTeam) {
      console.error('Invalid auction data:', { teams, selectedUserTeam });
      setError('Failed to start auction. Please try again.');
      return;
    }
    setUserTeam(selectedUserTeam);
    setFinalTeams(teams);
    setRoomCode(roomCodeParam); // Keep room code for multiplayer sync
    setGameState('auction');
  }, []);

  const handleAuctionEnd = useCallback((teams: Team[]) => {
    setFinalTeams(teams);
    setGameState('summary');
  }, []);
  
  const handleRestart = useCallback(() => {
    setGameState('lobby');
    setUserTeam(null);
    setFinalTeams([]);
    setRoomCode(null);
    setIsRoomHost(false);
    setError(null);
  }, []);

  return (
    <div className="bg-gray-900 text-white min-h-screen font-sans overflow-x-hidden">
      {error && (
        <div className="fixed top-4 right-4 bg-red-600 text-white px-6 py-3 rounded-lg shadow-lg z-50 flex items-center gap-3">
          <span>{error}</span>
          <button onClick={() => setError(null)} className="text-xl font-bold">&times;</button>
        </div>
      )}
      <AnimatePresence mode="wait">
        {gameState === 'landing' && (
          <LandingPage key="landing" onGetStarted={handleGoToSignup} />
        )}
        {gameState === 'signup' && (
          <SignupPage key="signup" onSignup={handleSignup} />
        )}
        {gameState === 'lobby' && user && (
          <Lobby 
            key="lobby" 
            onStartSinglePlayer={handleStartSinglePlayer} 
            onGoToMultiplayer={handleGoToMultiplayer}
            username={user.username} 
          />
        )}
        {gameState === 'multiplayer-home' && (
            <MultiplayerHome 
              key="multiplayer-home"
              onCreateRoom={handleCreateRoom}
              onJoinRoom={handleJoinRoom}
              onBack={handleGoToLobby}
            />
        )}
        {gameState === 'room-lobby' && user && roomCode && (
            <RoomLobby 
              key="room-lobby"
              roomCode={roomCode}
              username={user.username}
              isHost={isRoomHost}
              onStartAuction={handleStartMultiplayerAuction}
              onBack={handleGoToLobby}
            />
        )}
        {gameState === 'auction' && userTeam && user && finalTeams.length > 0 && (
          <AuctionRoom
            key="auction-room"
            initialTeams={finalTeams}
            userTeam={userTeam}
            username={user.username}
            onAuctionEnd={handleAuctionEnd}
            roomCode={roomCode || undefined}
          />
        )}
        {gameState === 'auction' && (!userTeam || !user || finalTeams.length === 0) && (
          <div className="flex items-center justify-center min-h-screen">
            <div className="text-center">
              <h1 className="text-3xl font-bold mb-4">Error Loading Auction</h1>
              <p className="text-gray-400 mb-6">Failed to load auction data. Please try again.</p>
              <button 
                onClick={() => setGameState('lobby')}
                className="bg-yellow-500 text-gray-900 font-bold py-2 px-6 rounded-lg hover:bg-yellow-400 transition-colors"
              >
                Back to Lobby
              </button>
            </div>
          </div>
        )}
        {gameState === 'summary' && (
          <AuctionSummary key="summary" teams={finalTeams} onRestart={handleRestart} />
        )}
      </AnimatePresence>
    </div>
  );
};

export default App;